# Regenerate assets/search-index.json and assets/search-index.js from all HTML pages.
# Run from repo root: powershell -File scripts/build-search-index.ps1

$root = Split-Path -Parent $PSScriptRoot
$pages = @()

function Strip-HtmlText([string]$html) {
  $text = $html -replace '<script[\s\S]*?</script>', ' '
  $text = $text -replace '<style[\s\S]*?</style>', ' '
  $text = $text -replace '<[^>]+>', ' '
  $text = $text -replace '&nbsp;', ' '
  $text = $text -replace '&amp;', ' and '
  $text = $text -replace '&[^;\s]+;', ' '
  $text = $text -replace '\s+', ' '
  return $text.Trim()
}

Get-ChildItem -Path $root -Filter "*.html" -Recurse | ForEach-Object {
  $rel = $_.FullName.Substring($root.Length + 1).Replace('\', '/')
  $html = Get-Content $_.FullName -Raw -Encoding UTF8

  if ($html -match '<title>([^<]+)</title>') { $title = $Matches[1].Trim() } else { $title = $_.BaseName }
  $title = $title -replace '\s*\|\s*Interview Prep\s*$', '' -replace '\s*\|\s*AI Engineering\s*$', '' -replace '\s*\|\s*Docker & Kubernetes\s*$', '' -replace '\s*\|\s*Graph Machine Learning\s*$', '' -replace '\s*-\s*AI Engineering\s*$', ''

  $desc = ''
  if ($html -match '<header>\s*[\s\S]*?<p>([^<]+)</p>') { $desc = $Matches[1].Trim() }

  $headings = [regex]::Matches($html, '<h2[^>]*>([^<]+)</h2>') | ForEach-Object {
    $_.Groups[1].Value.Trim() -replace '^\d+\.\s*', ''
  }

  $details = [regex]::Matches($html, '<summary>([^<]+)</summary>') | ForEach-Object { $_.Groups[1].Value.Trim() }

  $mainText = ''
  if ($html -match '<main[\s\S]*?</main>') {
    $mainText = Strip-HtmlText $Matches[0]
  }

  $type = 'page'
  if ($rel -match '/learn/') { $type = 'learn' }
  elseif ($rel -match '/interview/') { $type = 'interview' }
  elseif ($rel -match '/research/') { $type = 'research' }
  elseif ($rel -match 'index\.html$' -or $rel -match 'ai-engineering\.html$' -or $rel -match 'docker-kubernetes\.html$' -or $rel -match 'graph-ml\.html$' -or $rel -match 'research-hub\.html$' -or $rel -match 'papers-hub\.html$' -or $rel -match 'ai-engineering-interview\.html$' -or $rel -match 'docker-kubernetes-interview\.html$' -or $rel -match 'graph-ml-interview\.html$' -or $rel -match 'docker-kubernetes-cheatsheets\.html$' -or $rel -match 'graph-ml-formulas\.html$') {
    $type = 'hub'
  }

  $textParts = @($title, $desc) + $headings + $details + @($mainText)
  $joined = ($textParts -join ' ')
  $text = if ($joined.Length -gt 4000) { $joined.Substring(0, 4000) } else { $joined }

  $keywords = @()
  if ($html -match 'class="badge-interview"') { $keywords += 'interview' }
  if ($rel -match 'reinforcement') {
    $keywords += @('RL', 'reinforcement learning', 'PPO', 'DPO', 'GRPO', 'policy gradient', 'reward')
  }
  if ($rel -match 'rag') { $keywords += @('retrieval', 'augmented generation', 'RAG') }
  if ($rel -match 'transformer') { $keywords += @('attention', 'transformer', 'self-attention') }

  $pages += [ordered]@{
    path        = $rel
    title       = $title
    type        = $type
    description = $desc
    headings    = @($headings | Select-Object -First 50)
    keywords    = $keywords
    text        = $text
  }
}

$index = @{ pages = $pages }
$json = $index | ConvertTo-Json -Depth 6 -Compress:$false
$jsonPath = Join-Path $root 'assets/search-index.json'
[System.IO.File]::WriteAllText($jsonPath, $json)

$js = "// Auto-generated by scripts/build-search-index.ps1`nwindow.__SEARCH_INDEX__ = $json;`n"
$jsPath = Join-Path $root 'assets/search-index.js'
[System.IO.File]::WriteAllText($jsPath, $js)

Write-Host "Wrote $($pages.Count) pages to $jsonPath and $jsPath"
